### ISSUE TITLE
Suggestion: create multiple variable names for the same partials

### ISSUE THREAD

**Issue by bachilli** [creativeinflux/CodeIgniter-Flexi-Layout-Library#1]
Instead of creating multiple layouts, example: logged_in_template and logged_out_template to insert different "menus", you can use the same idea of Stencil template library: http://scotch.io/docs/stencil#slices (Custom paths);

**Comment by creativeinflux** [comment]
Partials is already a feature (http://creativeinflux.co.uk/lab/codeigniter_flexi_layout_library/partials.php) but doesn't include custom names or paths, shouldn't be too difficult to add in.  Thanks
